package view;

import dao.ProdukDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Kelompok 2
 * @ketua Farrel Risqullah Mahardika (25104410017)
 * @anggota Tegar Ludwinio Mahardhika (25104410001), Naufal Aqbil Hanif (25104410003), Muhamad Johan Putra Pratama (25104410007), Gerry Atha Himawan (25104410012), Ryz Nuzula Abdillah Nafis Azhar (25104410018), Syahreza Faiz Pratama (25104410093)
 */
public class FormProduk extends javax.swing.JFrame {
  
    //Panggil mesin DAO
    private ProdukDAO produkDAO = new ProdukDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormProduk.class.getName());

    /**
     * Creates new form FormProduk
     */
    public FormProduk() {
        initComponents();
        setLocationRelativeTo(null); // Biar aplikasi muncul di tengah layar
        loadTable(); // Panggil fungsi load saat aplikasi pertama kali dibuka
        
        tblProduk.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        // Kode untuk membuat aplikasi langsung Full Screen saat dibuka
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) tblProduk.getModel();
        model.setRowCount(0); // Kosongkan tabel dulu
        
        // produkDAO.getAllProduk() mengembalikan array dengan urutan dari SQL:
        // [0]=kode, [1]=nama, [2]=kategori, [3]=brand, [4]=harga, [5]=stock, [6]=kode_produk
        
        for (Object[] row : produkDAO.getAllProduk()) {
            // Susun ulang urutan agar pas dengan kolom tabel di form:
            // Kode, Nama Produk, Harga, Stock, Kategori, Brand
            Object[] tableRow = {
                row[0], // Kode
                row[1], // Nama Produk
                row[4], // Harga
                row[5], // Stock
                row[2], // Kategori
                row[3]  // Brand
            };
            model.addRow(tableRow);
            adjustTableHeight();
        }
    }
    
    public void adjustTableHeight() {
        int rowCount = tblProduk.getRowCount();
        int rowHeight = tblProduk.getRowHeight();
        int headerHeight = tblProduk.getTableHeader().getPreferredSize().height;    
        int totalHeight = (rowCount * rowHeight) + headerHeight + 5; 
    
        jScrollPane1.setPreferredSize(new java.awt.Dimension(jScrollPane1.getWidth(), totalHeight));
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelUtama = new javax.swing.JPanel();
        SistemInventoryMerchandiseAnime = new javax.swing.JLabel();
        panelKedua = new javax.swing.JPanel();
        btnLoad = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnbersihkan1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir Anime");

        panelUtama.setBackground(new java.awt.Color(246, 234, 212));
        panelUtama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kasir Anime v1.0", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelUtama.setLayout(new java.awt.GridBagLayout());

        SistemInventoryMerchandiseAnime.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SistemInventoryMerchandiseAnime.setForeground(new java.awt.Color(0, 0, 0));
        SistemInventoryMerchandiseAnime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SistemInventoryMerchandiseAnime.setText(" KASIR MERCHANDISE ANIME");
        SistemInventoryMerchandiseAnime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        panelUtama.add(SistemInventoryMerchandiseAnime, gridBagConstraints);

        panelKedua.setBackground(new java.awt.Color(0, 0, 0));
        panelKedua.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelKedua.setForeground(new java.awt.Color(255, 255, 255));
        panelKedua.setOpaque(false);

        btnLoad.setBackground(new java.awt.Color(162, 165, 149));
        btnLoad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLoad.setForeground(new java.awt.Color(0, 0, 0));
        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-16.png"))); // NOI18N
        btnLoad.setMnemonic('S');
        btnLoad.setText("Load");
        btnLoad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoad.addActionListener(this::btnLoadActionPerformed);

        btnInsert.setBackground(new java.awt.Color(162, 165, 149));
        btnInsert.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(0, 0, 0));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-edit-16.png"))); // NOI18N
        btnInsert.setMnemonic('E');
        btnInsert.setText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(this::btnInsertActionPerformed);

        btnUpdate.setBackground(new java.awt.Color(162, 165, 149));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-delete-16.png"))); // NOI18N
        btnUpdate.setMnemonic('H');
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("Pilih data di tabel terlebih dahulu, lalu klik untuk menghapus");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setBackground(new java.awt.Color(162, 165, 149));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eraser-16.png"))); // NOI18N
        btnDelete.setMnemonic('B');
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnKategori.setBackground(new java.awt.Color(162, 165, 149));
        btnKategori.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnKategori.setForeground(new java.awt.Color(0, 0, 0));
        btnKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-16.png"))); // NOI18N
        btnKategori.setText("Kategori");
        btnKategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKategori.addActionListener(this::btnKategoriActionPerformed);

        btnbersihkan1.setBackground(new java.awt.Color(162, 165, 149));
        btnbersihkan1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnbersihkan1.setForeground(new java.awt.Color(0, 0, 0));
        btnbersihkan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-about-16.png"))); // NOI18N
        btnbersihkan1.setMnemonic('B');
        btnbersihkan1.setText("About");
        btnbersihkan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbersihkan1.addActionListener(this::btnbersihkan1ActionPerformed);

        javax.swing.GroupLayout panelKeduaLayout = new javax.swing.GroupLayout(panelKedua);
        panelKedua.setLayout(panelKeduaLayout);
        panelKeduaLayout.setHorizontalGroup(
            panelKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeduaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbersihkan1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelKeduaLayout.setVerticalGroup(
            panelKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeduaLayout.createSequentialGroup()
                .addGroup(panelKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKeduaLayout.createSequentialGroup()
                        .addGroup(panelKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLoad)
                            .addComponent(btnInsert)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnKategori))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnbersihkan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 11, 0);
        panelUtama.add(panelKedua, gridBagConstraints);

        tblProduk.setBackground(new java.awt.Color(234, 214, 184));
        tblProduk.setForeground(new java.awt.Color(0, 0, 0));
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama Produk", "Harga", "Stock", "Kategori", "Brand"
            }
        ));
        tblProduk.setSelectionBackground(new java.awt.Color(246, 234, 212));
        tblProduk.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduk);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1090;
        gridBagConstraints.ipady = 286;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(40, 11, 0, 11);
        panelUtama.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked
        
    }//GEN-LAST:event_tblProdukMouseClicked

    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        new FormKategori().setVisible(true);
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tblProduk.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris produk yang ingin dihapus terlebih dahulu!");
            return;
        }
    
        // Ambil nilai "Kode" dari kolom ke-0 pada baris yang dipilih
        int kode = (int) tblProduk.getValueAt(baris, 0);
    
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus produk ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            if (produkDAO.delete(kode)) {
                JOptionPane.showMessageDialog(this, "Produk berhasil dihapus!");
                loadTable(); // Refresh tabel
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int baris = tblProduk.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih produk yang ingin diedit di tabel terlebih dahulu!");
            return;
        }

        // Ambil data dari tabel sesuai urutan kolom yang kita buat:
        // 0:Kode, 1:Nama, 2:Harga, 3:Stock, 4:Kategori, 5:Brand
        int kode = (int) tblProduk.getValueAt(baris, 0);
        String nama = tblProduk.getValueAt(baris, 1).toString();
        int harga = (int) tblProduk.getValueAt(baris, 2);
        int stock = (int) tblProduk.getValueAt(baris, 3);
        String kategori = tblProduk.getValueAt(baris, 4).toString();
        String brand = tblProduk.getValueAt(baris, 5).toString();

        // Buka pop-up DialogTambahProduk dan kirim data ke method setUpdateMode
        DialogTambahProduk dialog = new DialogTambahProduk(this, true);
        dialog.setTitle("Update Produk");
        dialog.setUpdateMode(kode, nama, harga, stock, kategori, brand);
        dialog.setVisible(true); 
        
        // Refresh tabel otomatis setelah pop-up ditutup
        loadTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // Membuka JDialog pop-up untuk menambah produk
        DialogTambahProduk dialog = new DialogTambahProduk(this, true);
        dialog.setTitle("Tambah Data Produk");
        dialog.setVisible(true); 
        
        // Refresh tabel otomatis setelah pop-up ditutup
        loadTable();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        loadTable();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnbersihkan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkan1ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            """
            1. Tegar Ludwinio Mahardhika (25104410001)
            2. Naufal Aqbil Hanif (25104410003)
            3. Muhamad Johan Putra Pratama (25104410007)
            4. Gerry Atha Himawan (25104410012)
            5. Farrel Risqullah Mahardika (25104410017)
            6. Ryz Nuzula Abdillah Nafis Azhar (25104410018)
            7. Syahreza Faiz Pratama (25104410093)
            """, 
            "Kelompok 2",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnbersihkan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormProduk().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SistemInventoryMerchandiseAnime;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnbersihkan1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelKedua;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTable tblProduk;
    // End of variables declaration//GEN-END:variables
}
