package view;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 * Kelompok 2
 * @ketua Farrel Risqullah Mahardika (25104410017)
 * @anggota Tegar Ludwinio Mahardhika (25104410001), Naufal Aqbil Hanif (25104410003), Muhamad Johan Putra Pratama (25104410007), Gerry Atha Himawan (25104410012), Ryz Nuzula Abdillah Nafis Azhar (25104410018), Syahreza Faiz Pratama (25104410093)
 */
public class FormKategori extends javax.swing.JFrame {
    
    private dao.KategoriDAO kategoriDAO = new dao.KategoriDAO();
    private int kodeKategoriEdit = 0; // Untuk menyimpan ID saat baris tabel diklik
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKategori.class.getName());

    /**
     * Creates new form FormKategori
     */
    public FormKategori() {
        initComponents();
        setLocationRelativeTo(null); // Agar form muncul di tengah layar
        loadTable(); // Panggil data kategori
        
        // Memaksa tulisan tabel yang diklik menjadi warna Hitam (RGB: 0, 0, 0)
        tblKategori.setSelectionForeground(new java.awt.Color(0, 0, 0));
        
        tblKategori.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        // Kode untuk membuat aplikasi langsung Full Screen saat dibuka
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
    private void loadTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblKategori.getModel();
        model.setRowCount(0); // Kosongkan tabel
        
        // Ambil data dari DAO lalu susun ke tabel
        for (model.Kategori k : kategoriDAO.getAllKategori()) {
            Object[] baris = {
                k.getKode(), 
                k.getKategori(), 
                k.getBrand()
            };
            model.addRow(baris);
            adjustTableHeight();
        }
    }
    public void adjustTableHeight() {
        int rowCount = tblKategori.getRowCount();
        int rowHeight = tblKategori.getRowHeight();
        int headerHeight = tblKategori.getTableHeader().getPreferredSize().height;    
        int totalHeight = (rowCount * rowHeight) + headerHeight + 5; 
    
        jScrollPane1.setPreferredSize(new java.awt.Dimension(jScrollPane1.getWidth(), totalHeight));
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        txtkategori = new javax.swing.JTextField();
        panelUtama = new javax.swing.JPanel();
        SistemInventoryMerchandiseAnime = new javax.swing.JLabel();
        panelKedua = new javax.swing.JPanel();
        btnload = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();

        jButton1.setText("OKE");

        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtkategori, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtkategori, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Kategori\n");

        panelUtama.setBackground(new java.awt.Color(246, 234, 212));
        panelUtama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kategori Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelUtama.setLayout(new java.awt.GridBagLayout());

        SistemInventoryMerchandiseAnime.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SistemInventoryMerchandiseAnime.setForeground(new java.awt.Color(0, 0, 0));
        SistemInventoryMerchandiseAnime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SistemInventoryMerchandiseAnime.setText("KATEGORI MERCHANDISE ANIME");
        SistemInventoryMerchandiseAnime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        panelUtama.add(SistemInventoryMerchandiseAnime, gridBagConstraints);

        panelKedua.setBackground(new java.awt.Color(255, 255, 255));
        panelKedua.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelKedua.setOpaque(false);

        btnload.setBackground(new java.awt.Color(162, 165, 149));
        btnload.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnload.setForeground(new java.awt.Color(0, 0, 0));
        btnload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-16.png"))); // NOI18N
        btnload.setMnemonic('S');
        btnload.setText("Load");
        btnload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnload.addActionListener(this::btnloadActionPerformed);

        btninsert.setBackground(new java.awt.Color(162, 165, 149));
        btninsert.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btninsert.setForeground(new java.awt.Color(0, 0, 0));
        btninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-edit-16.png"))); // NOI18N
        btninsert.setMnemonic('E');
        btninsert.setText("Insert");
        btninsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninsert.addActionListener(this::btninsertActionPerformed);

        btnDelete.setBackground(new java.awt.Color(162, 165, 149));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-delete-16.png"))); // NOI18N
        btnDelete.setMnemonic('H');
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Pilih data di tabel terlebih dahulu, lalu klik untuk menghapus");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnupdate.setBackground(new java.awt.Color(162, 165, 149));
        btnupdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 0, 0));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-pencil-16.png"))); // NOI18N
        btnupdate.setMnemonic('B');
        btnupdate.setText("Update");
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        javax.swing.GroupLayout panelKeduaLayout = new javax.swing.GroupLayout(panelKedua);
        panelKedua.setLayout(panelKeduaLayout);
        panelKeduaLayout.setHorizontalGroup(
            panelKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeduaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btninsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete))
        );
        panelKeduaLayout.setVerticalGroup(
            panelKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeduaLayout.createSequentialGroup()
                .addGroup(panelKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnload)
                    .addComponent(btninsert)
                    .addComponent(btnDelete)
                    .addComponent(btnupdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panelUtama.add(panelKedua, gridBagConstraints);

        tblKategori.setBackground(new java.awt.Color(234, 214, 184));
        tblKategori.setForeground(new java.awt.Color(0, 0, 0));
        tblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama Kategori", "Brand"
            }
        ));
        tblKategori.setSelectionBackground(new java.awt.Color(246, 234, 212));
        tblKategori.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKategori);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1058;
        gridBagConstraints.ipady = 196;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 11, 15);
        panelUtama.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
       // Pop-up 1: Meminta Nama Kategori
        String inputKategori = javax.swing.JOptionPane.showInputDialog(this, "Masukkan Nama Kategori", "Tambah Kategori", javax.swing.JOptionPane.QUESTION_MESSAGE);
    
        // Validasi: Jika user klik 'Cancel' atau membiarkannya kosong, maka hentikan proses
        if (inputKategori == null || inputKategori.trim().isEmpty()) {
            return; 
        }

        // Pop-up 2: Meminta Nama Brand (Hanya muncul jika pop-up pertama berhasil diisi)
        String inputBrand = javax.swing.JOptionPane.showInputDialog(this, "Masukkan Brand", "Tambah Brand", javax.swing.JOptionPane.QUESTION_MESSAGE);

        // Validasi: Jika user klik 'Cancel' atau membiarkannya kosong, maka hentikan proses
        if (inputBrand == null || inputBrand.trim().isEmpty()) {
            return; 
        }

        // Jika keduanya berhasil diisi, masukkan ke database
        model.Kategori k = new model.Kategori();
        k.setKategori(inputKategori);
        k.setBrand(inputBrand);

        if (kategoriDAO.insert(k)) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Kategori Berhasil Disimpan!");
            loadTable(); // Refresh tabel
        }
    }//GEN-LAST:event_btninsertActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int baris = tblKategori.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel terlebih dahulu yang ingin diedit!");
            return;
        }

        // Ambil ID dan data lama dari tabel
        int kode = (int) tblKategori.getValueAt(baris, 0);
        String kategoriLama = tblKategori.getValueAt(baris, 1).toString();
        String brandLama = tblKategori.getValueAt(baris, 2).toString();

        // Pop-up 1: Edit Kategori
        String inputKategori = (String) javax.swing.JOptionPane.showInputDialog(this, "Update Nama Kategori:", "Update Kategori", javax.swing.JOptionPane.QUESTION_MESSAGE, null, null, kategoriLama);
    
        // Validasi batal/kosong
        if (inputKategori == null || inputKategori.trim().isEmpty()) {
            return; 
        }

        // Pop-up 2: Edit Brand (Ada variabel 'brandLama' sebagai nilai awal)
        String inputBrand = (String) javax.swing.JOptionPane.showInputDialog(this, "Update Brand:", "Update Brand", javax.swing.JOptionPane.QUESTION_MESSAGE, null, null, brandLama);

        // Validasi batal/kosong
        if (inputBrand == null || inputBrand.trim().isEmpty()) {
            return; 
        }

        // Proses update ke database
        model.Kategori k = new model.Kategori();
        k.setKode(kode);
        k.setKategori(inputKategori);
        k.setBrand(inputBrand);

        if (kategoriDAO.update(k)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kategori Berhasil Diupdate!");
            loadTable();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        loadTable(); // Memanggil fungsi untuk me-refresh tabel
    }//GEN-LAST:event_btnloadActionPerformed

    private void tblKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKategoriMouseClicked
     int baris = tblKategori.getSelectedRow();
     if (baris != -1) {
         // Kita hanya perlu menyimpan ID-nya saja untuk patokan Update/Delete
         kodeKategoriEdit = (int) tblKategori.getValueAt(baris, 0); 
     }
    }//GEN-LAST:event_tblKategoriMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tblKategori.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin dihapus!");
            return;
        }
    
        int kode = (int) tblKategori.getValueAt(baris, 0);

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus kategori ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            // Jika kategori masih dipakai di produk, KategoriDAO akan memblokirnya secara otomatis
            if (kategoriDAO.delete(kode)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Kategori Berhasil Dihapus!");
                loadTable();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKategori().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SistemInventoryMerchandiseAnime;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelKedua;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTextField txtkategori;
    // End of variables declaration//GEN-END:variables

   
}
